apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-ns
data:
  # property-like keys; each key maps to a simple value
  DB_HOSTNAME: db.hostname
  # ui_properties_file_name: "user-interface.properties"

  # # file-like keys
  # game.properties: |
  #   enemy.types=aliens,monsters
  #   player.maximum-lives=5
  # user-interface.properties: |
  #   color.good=purple
  #   color.bad=yellow
  #   allow.textmode=true
